###
# file name: docker-compose.yml (Wavemotion-lightning)
# Author: Dr. Xiaoxian Guo @ Shanghai Jiao Tong University, China
# Email: xiaoxguo@sjtu.edu.cn
# Website: https://naoce.sjtu.edu.cn/teachers/9004.html
# Github: https://github.com/XiaoxG/waveMotion-lightning/
# Create date: 2021/10/08
# Wavemotion-lightning-- a demonstration code for wave motion prediction of an offshore platform. 
# Refers to preprint Arvix: "Probabilistic prediction of the heave motions of a semi-submersible by a deep learning model"
###

version: "3.9"

services:
  env:
    build: .
    volumes:
      - ".:/code:rw"
    tty: true        # docker run -t
    deploy:          # for gpu only
      resources:
        reservations:
          devices:
            - capabilities: [gpu]